micronaut:
  server:
    port: 9000
  application:
    name: sample-service
  function:
    name: sample-service
---
#tag::security[]
micronaut:
  security:
    intercept-url-map:
      - pattern: /**/**/**
        access:
          - isAuthenticated()
    authentication: bearer # <1>
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
---
#tag::refresh[]
micronaut:
  security:
    token:
      jwt:
        generator:
          refresh-token:
            secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
---
micronaut:
  io:
    watch:
      enabled: true
      paths: src/,res/,../connector/db/src,../core/src
      restart: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /open-api-specifications/**
---
graphql:
  graphiql:
    enabled: true

